[package]
name = "file-monitor-agent"
version = "0.1.5"
edition = "2024"
authors = ["Rafal Curzydlo <rafalcurzydlo.biz@gmail.com>"]
description = "Agent do monitorowania plikow i synchronizacji z baza danych."
license = "MIT"
repository = "https://github.com/Szadolowski/monitoring_app"

[package.metadata.wix]
upgrade-guid = "48C5CDCF-A086-41E5-A72B-ED85F89B7C9A"
path-guid = "408CAA29-F094-4D27-9E69-760C1EB8B3A2"
license = false
eula = false

[dependencies]
tokio = { version = "1.52.2", features = ["full"] }
sqlx = { version = "0.8.6", features = ["runtime-tokio-native-tls", "postgres", "macros", "chrono"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
directories = "6.0.0"
notify = "8.2.0"
tray-icon = "0.23.1"
tao = "0.35.2"
thiserror = "2.0.18"
anyhow = "1.0"
tracing = "0.1"
tracing-subscriber = "0.3"
dotenvy = "0.15.7"
walkdir = "2.5.0"
eframe = "0.34.2"
chrono = "0.4.44"
bcrypt = "0.19.0"

[profile.dist]
inherits = "release"
lto = "thin"