name: Budowa Instalatora Windows

# Uruchom ten proces TYLKO wtedy, gdy dodasz nowy tag (np. v0.1.5)
on:
  push:
    tags:
      - "v*"

# Nadajemy uprawnienia do tworzenia wydań (Releases)
permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
      - name: Pobranie kodu z repozytorium
        uses: actions/checkout@v4

      - name: Instalacja Rusta
        uses: dtolnay/rust-toolchain@stable

      - name: Kompilacja programu (Release)
        run: cargo build --release

      - name: Instalacja Inno Setup na serwerze GitHuba
        run: choco install innosetup

      - name: Budowa Instalatora (Inno Setup)
        run: iscc instalator.iss

      - name: Publikacja gotowego .exe na GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          files: Instalator/FileMonitorAgent_Setup.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
